version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    container_name: fastapi_app
    command: uvicorn project.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env

  bot:
    build: .
    container_name: telegram_bot
    command: python3 project/bot.py
    volumes:
      - .:/app
    depends_on:
      - app
    env_file:
      - .env
